### ISSUE TITLE
http://IP/wx 微信提示配置失败

### ISSUE THREAD

**Issue by lywly** [brucx/mp-push-nestjs#1]
端口不是80，用了另外一个，不知道是不是这个原因

**Comment by brucx** [comment]
那你试试带上端口号http://IP:PORT/wx

**Comment by lywly** [comment]
也测试过了，我怀疑是服务器没有备案的原因。换用Lean Cloud弄好了（以前申请的应用，还能用到10月。。。。）

**Comment by brucx** [comment]
可以试试海外服务器

**Comment by lywly** [comment]
还是学生机便宜啊……海外有推荐的吗

**Comment by brucx** [comment]
给个邮箱，给你一台主机

**Comment by lywly** [comment]
我擦，这么好的吗...
github@aily.top

**Comment by brucx** [comment]
已经发送，查收。
spend your time doing something worthwhile

**Comment by lywly** [comment]
感谢感谢
