### ISSUE TITLE
token 不能为空，设置后校验不正确

### ISSUE THREAD

**Issue by iamsee** [brucx/mp-push-nestjs#8]
![image](https://user-images.githubusercontent.com/6944557/97306757-dc4c8f80-1899-11eb-914a-3b0b44a12c75.png)
连接是正确的
![image](https://user-images.githubusercontent.com/6944557/97306846-f6866d80-1899-11eb-9c96-0b332ded58e6.png)

**Comment by brucx** [comment]
路径为 /wx

**Comment by iamsee** [comment]
解决了，还是80端口的问题，谢谢回复

**Comment by iamsee** [comment]
在麻烦问一下作者，如果想给指定的人推送消息应该用什么接口呢，不可能是一人一个模板吧

**Comment by iamsee** [comment]
@brucx
